# makefile

BINDIR = ../../bin

CC=gcc
CFLAGS= -g -I../../include `sdl-config --cflags`
LIBS= ../../lib/libgp.a ../../lib/libgutil.a ../../lib/libgeom.a ../../lib/libaux.a -framework OpenGL

SDLLIBS=`sdl-config --libs`

BIN = tk

tk:	main.o tk.o
	$(CC) -g -o tk main.o tk.o $(LIBS) $(SDLLIBS)

install: $(BIN)
	mv $(BIN) $(BINDIR)

clean:
	rm -f *.o tk

