BIN 	   = rsurf
OBJS	   = main.o
HDRS	   =

CGBIN	   = ../../bin
CGLIB	   = ../../lib
CGINCLUDE  = ../../include
INCLUDE	   = -I$(CGINCLUDE)

LIBCG      = $(CGLIB)/libgener.a $(CGLIB)/libpoly.a $(CGLIB)/liblang.a \
	$(CGLIB)/libgeom.a $(CGLIB)/libaux.a 
LIBUNIX	    = -lm
LIBS = $(LIBCG) $(LIBUNIX)

CC = gcc
CFLAGS = -g  $(INCLUDE)


$(BIN): main.o
	gcc -o $(BIN)  main.o $(LIBS)

install: $(BIN)
	mv $(BIN) $(CGBIN)

clean:
	rm -f *.o *~ $(BIN)

