# makefile
# Luiz Henrique de Figueiredo
# 04 Mar 93

BINDIR = ../../bin

CC=gcc
CFLAGS= -g -I../../include  `sdl-config --cflags`
LIBS= ../../lib/libgp.a ../../lib/libgutil.a ../../lib/libgeom.a ../../lib/libaux.a -L/usr/local/lib -lGL -lGLU
SDLLIBS=`sdl-config --libs`

BIN = ple

ple:	main.o
	$(CC) -g -o ple main.o $(LIBS) $(SDLLIBS)

testgl: testgl.c
	      $(CC) -o $@ $? $(CFLAGS) $(LIBS) -L/usr/X11/lib 


install: $(BIN)
	mv $(BIN) $(BINDIR)

clean:
	rm -f *.o ple

