# makefile
# Luiz Henrique de Figueiredo
# 04 Mar 93

BINDIR = ../../bin

CC=gcc
CFLAGS= -g -I../../include `sdl-config --cflags`
LIBS= ../../lib/libgp.a ../../lib/libgutil.a ../../lib/libgeom.a ../../lib/libaux.a -framework OpenGL

SDLLIBS=`sdl-config --libs`

BIN = ple

ple:	main.o
	$(CC) -g -o ple main.o $(LIBS) $(SDLLIBS)

install: $(BIN)
	mv $(BIN) $(BINDIR)

clean:
	rm -f *.o ple

